<a href="https://colab.research.google.com/github/PromitHal/Pytorch/blob/master/Pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x=torch.ones(2,2,dtype=torch.float16)
print(x)
print(x.type)
print(x.size())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
<built-in method type of Tensor object at 0x7f183323db90>
torch.Size([2, 2])


In [2]:
x=torch.rand(2,2)
print(x)
y=torch.rand(2,2)
print(y)
#z=x+y also works
z=torch.add(x,y)
print(z)
z=torch.sub(x,y)
print(z)
#z=x*y
z=torch.mul(x,y)
print(z)

tensor([[0.2302, 0.1826],
        [0.4377, 0.9462]])
tensor([[0.1615, 0.1301],
        [0.9787, 0.8397]])
tensor([[0.3917, 0.3126],
        [1.4163, 1.7859]])
tensor([[ 0.0687,  0.0525],
        [-0.5410,  0.1064]])
tensor([[0.0372, 0.0237],
        [0.4283, 0.7945]])


In [3]:
import random
random.seed(42)
x=torch.rand(5,3)
print(x)
print(x[:,0])

tensor([[0.9680, 0.2712, 0.8106],
        [0.2872, 0.3202, 0.2240],
        [0.5420, 0.7222, 0.5535],
        [0.9197, 0.6836, 0.9692],
        [0.1672, 0.6501, 0.0802]])
tensor([0.9680, 0.2872, 0.5420, 0.9197, 0.1672])


In [5]:
random.seed(43)
x=torch.rand(5,3)
print(x)
print(x[0,:])

tensor([[0.6498, 0.6304, 0.8202],
        [0.9786, 0.3189, 0.0595],
        [0.2887, 0.3384, 0.7527],
        [0.8992, 0.7945, 0.1680],
        [0.7469, 0.6911, 0.0877]])
tensor([0.6498, 0.6304, 0.8202])


In [7]:
# Same location in memory
import numpy as np
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)
a+=1
print(a)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
